Inventory/urls.py
from django.contrib import admin
from django.urls import path,include
from register import views as v


urlpatterns = [
    path('admin/', admin.site.urls),
    path('data/',include('data.urls')),
    path('csv/',include('csvs.urls')),
    path("register/", v.register, name="register"),
	path('', v.loginPage, name="login"),  
    path('logout/', v.logoutUser, name="logout"),
]

csvs/urls.py
from django.urls import path

from .views import *

app_name = 'csvs'
urlpatterns = [
    path('',upload_file_view,name='upload_view'),

]

data/urls.py
from django.urls import path

from .views import *

app_name = 'data'
urlpatterns = [
    path('items/',items_list,name='items_list_url'),
    path('demand/',demand_list,name='demand_list_url'),
    path('calculations/',calculations,name='calculations_url'),



    path('demand/create/',DemandCreate,name='demand_create_url'),
    path('item/create/',ItemCreate,name='item_create_url'),

    path('delete_items/<str:pk>/', delete_items, name="delete_items"),
    path('update_item/<str:pk>/',update_items,name="update_item"),


# path('view/',view,name="view"),




    


]

data/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
import math
import scipy.stats as st
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

# Create your models here

def validate_even(value):
    if value > 100 or value == 0:
        raise ValidationError(
            _('%(value)s is not in between 0 and 100 percent'),
            params={'value': value},
        )
def validate_zero(value):
    if value == 0:
        raise ValidationError(
            _('%(value)s cant be zero'),
            params={'value': value},
        )




class Items(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True,related_name="items")
    name =models.CharField(max_length=150)
    lead_time=models.PositiveIntegerField(default='5',blank=True,null=True,validators=[validate_zero])
    service_level=models.PositiveIntegerField(default='95',blank=True,null=True,validators=[validate_even])
    standard_deviation=models.PositiveIntegerField(default='0',blank=True,null=True)
    carrying_cost=models.PositiveIntegerField(default='15',blank=False,validators=[validate_even],help_text='Enter as percentage of unit cost')
    ordering_cost=models.PositiveIntegerField(default='0',blank=False,null=True)
    unit_costprice=models.PositiveIntegerField(default='0',blank=False,null=True,validators=[validate_zero])
    average_daily_demand=models.PositiveIntegerField(default='0',blank=False,null=True)
    total_inventory=models.IntegerField(default='0',blank=True,null=True)
    eoq=models.IntegerField(default='0',blank=True,null=True)
    no_of_workingdays=models.IntegerField(default='0',blank=True,null=True)
    rq=models.IntegerField(default='0',blank=True,null=True)
    z=models.DecimalField(max_digits=4,decimal_places=3,default='0',blank=True,null=True)
 
    
    
    def __str__(self):
        return "{}".format(self.name)
    

    def save(self, *args, **kwargs):
        self.name = self.name.upper()
        self.eoq = math.sqrt((2*self.no_of_workingdays*self.average_daily_demand*self.ordering_cost)/(self.unit_costprice*(self.carrying_cost/100)))
        self.z=(st.norm.ppf(self.service_level/100))
        self.rq=(self.lead_time*self.average_daily_demand)+(self.z*self.standard_deviation*(self.lead_time))
        return super().save(*args, **kwargs)

    """def save(self,*args,**kwargs):
        self.z=int((st.norm.ppf(self.service_level/100)))*1000
        return super().save(*args, **kwargs)"""
    """def save(self,*args,**kwargs):
        self.lt=(math.sqrt(self.lead_time))*1000
        return super().save(*args, **kwargs)

    def save(self,*args,**kwargs):
        self.rq=(self.lead_time*self.average_daily_demand)+(self.z*self.standard_deviation*(self.lt))/1000000
        return super().save(*args, **kwargs)"""

    





class Demand(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True,related_name="demand")
    item=models.ForeignKey('Items', on_delete=models.CASCADE,related_name="demands")
    issue_quantity=models.IntegerField(blank=False,null=True)
    price=models.PositiveIntegerField(blank=False,null=True)
    recieve_quantity=models.IntegerField(default='0',blank=False,null=True)
    date=models.DateField(default=timezone.now,editable=True)


        
    
    def __str__(self):
        return "sold {} {} on {}".format(self.issue_quantity,self.item.name,self.date)
    


        



    

data/forms.py
from os import name
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db.models import fields
from django.http import request

from .models import Items,Demand


class ItemsForm(forms.ModelForm):
    class Meta:
        model =Items
        fields=['name','average_daily_demand','unit_costprice','carrying_cost','ordering_cost','total_inventory','lead_time','service_level','standard_deviation','no_of_workingdays']
    def clean_name(self):
      name=self.cleaned_data.get('name').upper()

      """if not name:
        raise forms.ValidationError('Fill This Field')
      for i in Items.objects.all():
        if i.name == name:
          raise forms.ValidationError(name + '  is already exists')"""
      return name

class DemandForm(forms.ModelForm):
  class Meta:
    model=Demand
    fields='__all__'
    exclude={'user'}
  def __init__(self,user=None,*args,**kwargs):
    super(DemandForm,self).__init__(*args,**kwargs)
    if user:
      self.fields['item'].queryset=Items.objects.filter(user=user)
class ItemSearchForm(forms.ModelForm):
   class Meta:
     model = Items
     fields = ['name']
"""class IssueForm(forms.ModelForm):
  class Meta:
    model=Demand
    fields=['issue_quantity','price']"""








#title.widget.attrs.update({'class':'form-control'})
#slug.widget.attrs.update({'class':'form-control'})

#def clean_slug(self):
#new_slug=self.cleaned_data.get('name').lower()
#if new_slug=='create':
#raise ValidationError ('slug may not be created')
#return new_slug

    

data/views.py
import math
from django.contrib.auth.models import User
from django.db.models.aggregates import Avg, StdDev,Sum,Variance
from django.db.models.expressions import F
from django.shortcuts import get_object_or_404, render
from numpy.core.fromnumeric import product
from .models import Items,Demand
import pandas as pd
import numpy as np
from django.views.generic import TemplateView
from .forms import *
from django.views.generic import View
from django.shortcuts import redirect
from django.shortcuts import reverse
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.core.exceptions import ValidationError



# Create your views here.
@login_required(login_url='login')
def items_list(request):
    ite=None
    total=None

    try:
        ite=request.user.items.all()
    except ObjectDoesNotExist:
        messages.info(request,"There is no items.")
    form = ItemSearchForm(request.POST or None)

    if request.method == 'POST':
            try:
                ite = request.user.items.filter(name__icontains=form['name'].value())
            except ObjectDoesNotExist:
                messages.info(request,"There is no items.")
    return render(request,'data/items_list.html',context = {"form": form,"items":ite,"total":total})


@login_required(login_url='login')
def demand_list(request,*args,**kwargs):
    itee=None
    try:
        itee=request.user.demand.all()
    except ObjectDoesNotExist:
        messages.info(request,"There is no demand")
    return render(request,'data/demand_list.html',context={'demand':itee})


@login_required(login_url='login')
def DemandCreate(request):
        form=DemandForm(request.user)
        if request.method == 'POST':
            form=DemandForm(request.user,request.POST) 
            if form.is_valid():
                n = form.cleaned_data["item"]
                l = form.cleaned_data["issue_quantity"]
                c = form.cleaned_data["price"]
                o = form.cleaned_data["recieve_quantity"]
                d = form.cleaned_data["date"]

                reporter = request.user.items.get(name=n)
                reporter.total_inventory = F('total_inventory')-l+o
                reporter.save()
                t = Demand(item=n,issue_quantity=l,price=c,recieve_quantity=o,date=d)
                t.save()
                request.user.demand.add(t)

                return redirect('data:demand_create_url')
                    
        return render(request,'data/demand_create.html',context={'form':DemandForm(request.user) })


@login_required(login_url='login')
def ItemCreate(request):
        form=ItemsForm()
        if request.method == 'POST':
            form=ItemsForm(request.POST) 
            if form.is_valid():
                n = form.cleaned_data["name"]
                l = form.cleaned_data["lead_time"]
                c = form.cleaned_data["carrying_cost"]
                o = form.cleaned_data["ordering_cost"]
                t = form.cleaned_data["total_inventory"]
                u = form.cleaned_data["unit_costprice"]
                s = form.cleaned_data["service_level"]
                w = form.cleaned_data["no_of_workingdays"]
                d = form.cleaned_data["standard_deviation"]
                a = form.cleaned_data["average_daily_demand"]

                for i in request.user.items.all():
                    if i.name==n:
                        messages.error(request, n +' Item Already Created')
                        return redirect('data:item_create_url')


                

                t = Items(name=n,lead_time=l,average_daily_demand=a,carrying_cost=c,ordering_cost=o,total_inventory=t,unit_costprice=u,service_level=s,no_of_workingdays=w,standard_deviation=d)
                t.save()
                request.user.items.add(t) 
                messages.success(request, n +' Item Created')
                return redirect('data:items_list_url')
                    
        return render(request,'data/item_create.html',context={'form':form })



@login_required(login_url='login')
def delete_items(request,pk):
    query_set=Items.objects.get(id=pk)
    if request.method=='POST':
        query_set.delete()
        messages.success(request,query_set.name + ' Removed')
        return redirect('data:items_list_url')
    context={'item':query_set.name}
    return render(request,'data/delete_items.html',context)


@login_required(login_url='login')
def update_items(request,pk):
    query_set=Items.objects.get(id=pk)
    form=ItemsForm(instance=query_set)
    n=query_set.name
    if request.method=='POST':
        form=ItemsForm(request.POST,instance=query_set)
        if form.is_valid():
            form.save()
            messages.info(request, n + '  Updated to ' + query_set.name)
            return redirect('data:items_list_url')
    context={'form':form}
    return render(request,'data/update_item.html',context)



@login_required(login_url='login')
def calculations(request):
    item_df=pd.DataFrame(Items.objects.all().values().filter(user=request.user))
    demand_df=pd.DataFrame(Demand.objects.all().values().filter(user=request.user))
    if demand_df.shape[0]>0:
        item_df['item_id']=item_df['id']
        df=pd.merge(item_df,demand_df,on='item_id').drop(['id_y','id_x','carrying_cost','ordering_cost','unit_costprice','lead_time','service_level','standard_deviation','average_daily_demand','total_inventory','eoq','no_of_workingdays','rq','z','user_id_y','price','recieve_quantity'],axis=1).rename({'item_id':'id'},axis=1)
        del df['user_id_x']
        del df['id']
        df.rename(columns = {'date':'End of the Month'}, inplace = True)
        df.rename(columns = {'name':'Item Name'}, inplace = True)
        df['End of the Month'] = pd.to_datetime(df['End of the Month'])
        df = df.groupby([pd.Grouper(key='End of the Month', freq='1M'),'Item Name']).aggregate({'issue_quantity':['mean','std','count','sum']}) # groupby each 1 month
        df.rename(columns = {'issue_quantity':'Demand'}, inplace = True) 
        df.rename(columns = {'mean':'Daily Average'}, inplace = True) 
        df.rename(columns = {'std':'Standard deviation'}, inplace = True) 
        df.rename(columns = {'count':'Frequency'}, inplace = True) 
        df.rename(columns = {'sum':'Total Demand'}, inplace = True) 
        df=df.to_html(classes=('table table-striped'))
        



        return render(request,'data/calculations.html',context={'df2':df})
    else:
        error='<h3>No Data to Analyze</h3>'
        return render(request,'data/calculations.html',context={'df2':error})






	
	



"""def issue_items(request, pk):
    queryset = Items.objects.get(id=pk)
    form=IssueForm()

    if request.method=='POST':
        form=IssueForm(request.POST,instance=queryset)
        if form.is_valid():
            queryset.total_inventory -= queryset.issue_quantity
            form.save()

            return redirect('data:items_list_url')
    context = {"queryset":queryset,"form":form}
    return render(request, "data/add_items.html", context)"""

"""def add_inventory(request, pk):
    queryset = Items.objects.get(id=pk)
    form=IssueForm()

    if request.method=='POST':
        form=IssueForm(request.POST,instance=queryset)
        if form.is_valid():
            queryset.total_inventory += queryset.issue_quantity
            form.save()

            return redirect('data:items_list_url')
    context = {"queryset":queryset,"form":form}
    return render(request, "data/add_inventory.html", context)"""







    

data/templates/data/add_inventory.html
{% extends 'data/base_blog.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Add Inventory</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" name="Submit">
    </form>
{% endblock %}

data/templates/data/add_items.html
{% extends 'data/base_blog.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>issue</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" name="Submit">
    </form>
{% endblock %}

data/templates/data/base_blog.html
  
{% extends 'base.html' %}

data/templates/data/calculations.html
{% extends 'data/base_blog.html' %}

{% block title  %}
    Items List
{% endblock %}

{% block content  %}



{{df2|safe}}


{% endblock %}

data/templates/data/chart.html
{% extends 'data/base_blog.html' %}






{% block content  %}
<h1>Pie Chart Population</h1>

  <canvas id="myChart" width="400" height="400"></canvas>

 <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script><script>
var ctx = document.getElementById('myChart');
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
        datasets: [{
            label: '# of Votes',
            data: [12, 19, 3, 5, 2, 3],
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero: true
                }
            }]
        }
    }
});
 </script>

  {{ df | safe}}


  <form action="{% url 'chart_url' %}" method="post" class="ui form">
      {% csrf_token %}

      <div class="fields">
        <div class="two fields">
          <label for="">date from :</label>
          <input type="date" name="date_from">
        </div>
        <div class="fields">
          <label for="">date to:</label>
          <input type="date" name="date_to">
        </div>
      </div>

      <button type="submit" name="button">Sunmit</button>
  </form>




          
{% endblock %}

data/templates/data/delete_items.html
{% extends 'data/base_blog.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <h1>Are you sure you want to delete.......... Item :  {{ item }}</h1><br>
        <input class="btn btn-danger" type="submit" value="Yes" />
        <a href="{% url 'data:items_list_url' %}"><div class="btn btn-primary">Cancel</div></a>
    </form>


{% endblock %}

data/templates/data/demand_create.html
{% extends 'data/base_blog.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Sales</h1>
    <br>
    <br>
    {% for message in messages %}
        <div class="alert alert-danger" role="alert">
          {{message}}
        </div>
    {%endfor%}
    <form method='POST' action=''>
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" class="btn btn-info" value='Create'/>
    </form>
{% endblock %}

data/templates/data/demand_list.html
{% extends 'data/base_blog.html' %}

{% block title  %}
    Items List
{% endblock %}

{% block content  %}




    <table class="table table-striped">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Price</th>
          <th scope="col">Quantity</th>
          <th scope="col">Time</th>

        </tr>
      </thead>
      {% for d in demand %}
      <tbody>
        <tr>
          <th scope="row">{{ d.item.name }}</th>
          <td>{{ d.price }}</td>
          <td>{{d.issue_quantity}}</td>
          <td>{{d.date}}</td>




        </tr>
      </tbody>
      {% endfor %}
  </table>

{% endblock %}

data/templates/data/item_create.html
{% extends 'data/base_blog.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Create Item</h1>
    <form method='POST' action=''>
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" class="btn btn-info" value='Create'/>
      </form>
    </form>
{% endblock %}

data/templates/data/items_list.html
  
{% extends 'data/base_blog.html' %}
{% load crispy_forms_tags %}
{% block title  %}
    Items List
{% endblock %}

{% block content  %}

{% for message in messages %}
  <div class="alert alert-danger" role="alert">
    {{message}}
  </div>
{%endfor%}
<form method='POST' action=''>{% csrf_token %}
  {{form|crispy}}
      <input type="submit" class="btn btn-info" value='Search'/>
</form>
<br>
  <a href="{% url 'data:items_list_url' %}" class="btn btn-primary btn-lg " role="button" >Show all Items</a>
  <a href="{% url 'data:item_create_url' %}" class="btn btn-secondary btn-lg "  role="button">Add new Item</a>



      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Inventory</th>
            <th scope="col">EOQ</th>
            <th scope="col">Reorder Quantity</th>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
            

          </tr>
        </thead>

    {% for item in items %}
        <tbody>
          <tr>

            <th scope="row">{{ item.name }}</th>
            <td>{{item.total_inventory}}</td>
            <td>{{item.eoq}}</td>
            <td>{{item.rq}}</td>
            <td><a href="{% url 'data:update_item' item.id %}" class="btn btn-outline-secondary" role="button">Update</a></td>
            <td><a href="{% url 'data:delete_items' item.id %}" class="btn btn-outline-danger" role="button">Delete</a></td>




          </tr>
        </tbody>
    {% endfor %}
      </table>



{% endblock %}

data/templates/data/update_item.html
{% extends 'data/base_blog.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h1>Update Item</h1>
    <br>
    <br>
    {% for message in messages %}
        <div class="alert alert-danger" role="alert">
          {{message}}
        </div>
    {%endfor%}
    <form method='POST' action=''>
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" class="btn btn-info" value='Create'/>
    </form>
{% endblock %}

data/templates/data/view.html
{% extends 'data/base_blog.html' %}

{% block title %}
View
{% endblock %}

{% block content %}
    {% for td in user.todolist.all %}
	<p>{{td.name}}</p>
    {% endfor %}
{% endblock %}