Inventory/urls.py
from django.contrib import admin
from django.urls import path,include
from register import views as v


urlpatterns = [
    path('admin/', admin.site.urls),
    path('data/',include('data.urls')),
    path('csv/',include('csvs.urls')),
    path("register/", v.register, name="register"),
	path('', v.loginPage, name="login"),  
    path('logout/', v.logoutUser, name="logout"),
]

csvs/urls.py
from django.urls import path

from .views import *

app_name = 'csvs'
urlpatterns = [
    path('',upload_file_view,name='upload_view'),

]

data/urls.py
from django.urls import path

from .views import *

app_name = 'data'
urlpatterns = [
    path('items/',items_list,name='items_list_url'),
    path('demand/',demand_list,name='demand_list_url'),
    path('calculations/',calculations,name='calculations_url'),



    path('demand/create/',DemandCreate,name='demand_create_url'),
    path('item/create/',ItemCreate,name='item_create_url'),

    path('delete_items/<str:pk>/', delete_items, name="delete_items"),
    path('update_item/<str:pk>/',update_items,name="update_item"),


# path('view/',view,name="view"),




    


]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>
        {% block title %}
          Inventory Project
        {% endblock %}

    </title>
</head>
<body>




<style>
  .hello-msg{
    font-size: 18px;
    color: #fff;
    margin-right: 20px;
  }
</style>
{% if user.is_authenticated %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'data:demand_list_url' %}">History</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'data:items_list_url' %}">Inventory Data</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'data:demand_create_url' %}">Sales</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'data:calculations_url' %}">Analysis</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'csvs:upload_view' %}">CSV Upload</a>
      </li>
    </ul>
  </div>

  <span class="hello-msg">Welcome , {{  request.user}}</span>
  <span ><a  class="hello-msg" href="{% url 'logout' %}">Logout</a></span>
{% endif %}
</nav>



        </ul>

      </div>
</nav>
    <div class="container mt-5">
        <div class="row">
            <div class="col-6 offset-md-2">




              {% block content %}
              
              {%  endblock %}

          </div>



    </div>
</body>
</html>